#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 4
fi

export BORG_REPO=/bak

if [ -e "/root/.borg_secret" ]; then
    . /root/.borg_secret
else
    exit 3
fi
RED=$(tput setaf 9)
BLUE=$(tput setaf 4)
NORMAL=$(tput sgr0)
info() { printf "$RED%s $BLUE%s$NORMAL\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

borg create                         \
    --filter AME                    \
    --stats                         \
    --umask 0022                    \
    --compression zstd              \
    --exclude-caches                \
    --exclude '/dev/*'              \
    --exclude '/proc/*'             \
    --exclude '/sys/*'              \
    --exclude '/tmp/*'              \
    --exclude '/run/*'              \
    --exclude '/mnt/*'              \
    --exclude '/media/*'            \
    --exclude '/lost+found'         \
    --exclude '/home/*'             \
    --exclude '/bak/*'              \
    ::'{hostname}-{now}'            \
    /                               \

backup_exit=$?

info "Pruning repository"

borg prune                      \
    --list                      \
    --prefix '{hostname}-'      \
    --show-rc                   \
    --keep-daily 7              \
    --keep-monthly 6            \

prune_exit=$?

global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}
