alias ls='exa --icons --sort=type'
alias la='ls -a'
alias lsl='ls -l --group'
alias lal='la -l --group'
alias ip='ip --color=auto'
alias t='trash'
alias cd='z'
alias conf='dash -c "cd $HOME/dotfiles; nvim"'
alias wiki='dash -c "cd $HOME/Documents/vimwiki; nvim index.md"'
alias diary='dash -c "cd $HOME/Documents/vimwiki; nvim diary/diary.md"'
