alias vim='nvim'
alias ls='exa -lF --sort=type --color=always'
alias la='exa -alF --sort=type'
alias top='btm'                 # this is kinda funny
alias ip='ip --color=auto'
alias t='trash'

alias cd.1='cd ../'
alias cd.2='cd ../../'
alias cd.3='cd ../../../'
alias cd.4='cd ../../../../'
alias cd.5='cd ../../../../../'

alias gad='git add'
alias gpl='git pull'
alias gph='git push'
alias gca='git commit -v -a'
alias gco='git commit'
alias gcm='git checkout main'
alias gcM='git checkout master'
alias gba='git branch all'
alias gmg='git merge'
alias grb='git rebase'
alias gbr='git branch'
