alias vim='nvim'
alias ls='exa -lF --sort=type --color=always'
alias la='exa -alF --sort=type'
alias ip='ip --color=auto'
alias t='trash'
alias cd='z'
alias vimconf='dash -c "cd $HOME/.config/nvim; nvim init.vim"'
