format = """ $directory\
$git_branch\
$git_commit\
$git_state\
$python\
$jobs\
$status\
$character"""
add_newline = false

[directory]
style = "purple"

[python]
format = '[(\($virtualenv\) )]($style)'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✕](bold red)'

[status]
format = '[\[$status\]]($style) '
disabled = false
