#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends --config "$HOME/.config/picom/picom.conf" &
pgrep -x polybar > /dev/null || "$HOME/.config/polybar/grayblocks/launch.sh"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         5
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox state=monocle
bspc rule -a Screenkey manage=off

bspc config focused_border_color                "#458588"
bspc config normal_border_color                 "#282828e6"

# wallpaper
if [ -s "$HOME/.fehbg" ]; then
    source "$HOME/.fehbg" 2>/dev/null
elif [ -e "$HOME/Pictures/background.png" ]; then
    feh --bg-fill --randomize --recursive "$HOME/Pictures/Wallpapers"
fi

