#!/bin/sh

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap 7

bspc config normal_border_color "#282828"
bspc config focused_border_color "#D79921"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -a Screenkey manage=off

pgrep -x sxhkd > /dev/null || sxhkd &

[ -e $HOME/.fehbg ] && $HOME/.fehbg
systemctl --user start wallpaper.timer
systemctl --user start dunst.service

killall -q polybar
while pgrep -u $(id -ru) -x polybar > /dev/null ; do sleep 0.5 ; done
polybar main --config="$HOME/.config/polybar/config.ini" &

killall -q picom
while pgrep -u $(id -ru) -x picom > /dev/null ; do sleep 0.5 ; done
picom --experimental-backends --config "$HOME/.config/picom/picom.conf" &
