#!/bin/dash

xsetroot -cursor_name left_ptr &
xrdb -merge $HOME/.Xresources

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

bspc config normal_border_color "#282828"

# wallpaper
if [ -s "$HOME/.fehbg" ]; then
    $HOME/bin/change_wallpaper $(rg -o "'.*'" .fehbg | sed "s/'//g")
else
    $HOME/bin/random_wallpaper
fi

pgrep -x sxhkd > /dev/null || sxhkd &
"$HOME/bin/start_picom"
"$HOME/bin/start_polybar"
